Ajustes

diff --git a/.github/workflows/01-feature-ci.yml b/.github/workflows/01-feature-ci.yml
--- a/.github/workflows/01-feature-ci.yml
+++ b/.github/workflows/01-feature-ci.yml
@@ -45,41 +45,41 @@ jobs:
             exit 1
           fi
 
-    validate-project:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout source code
-          uses: actions/checkout@v2
+  validate-project:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout source code
+        uses: actions/checkout@v2
 
-        - name: Validate package.json
-          run: |
-            PACKAGE_NAME=$(cat package.json | jq -r '.name')
-            PRIVATE=$(cat package.json | jq -r '.private')
-            PUBLISH_CONFIG=$(cat package.json | jq '.publishConfig')
-            REPOSITORY=$(cat package.json | jq '.repository')
-            VERSION=$(cat package.json | jq -r '.version')
+      - name: Validate package.json
+        run: |
+          PACKAGE_NAME=$(cat package.json | jq -r '.name')
+          PRIVATE=$(cat package.json | jq -r '.private')
+          PUBLISH_CONFIG=$(cat package.json | jq '.publishConfig')
+          REPOSITORY=$(cat package.json | jq '.repository')
+          VERSION=$(cat package.json | jq -r '.version')
 
-            if [[ ! ${PACKAGE_NAME} =~ ^@[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+$ ]]; then
-              echo "Error: attribute name is not in the format @<company>/<name>"
-              exit 1
-            fi
+          if [[ ! ${PACKAGE_NAME} =~ ^@[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+$ ]]; then
+            echo "Error: attribute name is not in the format @<company>/<name>"
+            exit 1
+          fi
 
-            if [[ ${PUBLISH_CONFIG} == "null" ]]; then
-              echo "Error: publishConfig is required"
-              exit 1
-            fi
+          if [[ ${PUBLISH_CONFIG} == "null" ]]; then
+            echo "Error: publishConfig is required"
+            exit 1
+          fi
 
-            if [[ ${REPOSITORY} == "null" ]]; then
-              echo "Error: repository is required"
-              exit 1
-            fi
+          if [[ ${REPOSITORY} == "null" ]]; then
+            echo "Error: repository is required"
+            exit 1
+          fi
 
-            if [[ ${PRIVATE} == "true" ]]; then
-              echo "Warning: private attribute is set to true, changing to false"
-              jq '.private = false' package.json > package.json.tmp && mv package.json.tmp package.json
-            fi
+          if [[ ${PRIVATE} == "true" ]]; then
+            echo "Warning: private attribute is set to true, changing to false"
+            jq '.private = false' package.json > package.json.tmp && mv package.json.tmp package.json
+          fi
 
-            echo "VERSION=${VERSION}" >> $GITHUB_ENV
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
 
   packages:
     timeout-minutes: 1
